title: Open Internet Manifest
description: A living manifesto for a free, open and decentralized internet

url: "https://openinternetmanifest.org"
baseurl: ""

include:
  - admin/
  - nl/guides/
  - nl/theses/
  - nl/social-posts/

defaults:
  - scope:
      path: "nl"
    values:
      lang: "NL"
  - scope:
      path: "en"
    values:
      lang: "EN"

collections:
  theses:
    output: true
    permalink: /theses/:slug/
  guides:
    output: true
    permalink: /guides/:slug/

exclude:
  - venv
  - tools
  - .git
  - .jekyll-cache
  - Gemfile.lock

# Forceer rebuild bij veranderingen
rebuild_trigger: v2026-03-27