#!/usr/bin/env python3
"""
update-clean-texts.py - Volledige rebuild van official-clean-texts.js
Gebruikt de schone clean_text uit de frontmatter.
"""

import re
import hashlib
from pathlib import Path

def escape_for_js(text):
    if not text:
        return ""
    text = text.replace('\\', '\\\\')
    text = text.replace('"', '\\"')
    text = text.replace('\n', '\\n')
    text = text.replace('\r', '')
    return text

def rebuild_clean_texts():
    js_file = Path("static/js/official-clean-texts.js")
    fuzzy_hashes = {}
    clean_texts = {}

    print("🔄 Rebuilding official-clean-texts.js from all posts...")

    patterns = ["_social-posts/nl/*.md", "_social-posts/en/*.md"]

    for pattern in patterns:
        for file_path in sorted(Path(".").glob(pattern)):
            content = file_path.read_text(encoding='utf-8')

            # Extract clean_text (multi-line)
            match = re.search(r'clean_text\s*:\s*\|-?\s*\n([\s\S]*?)(?=\n\w+\s*:|\n---\s*$|\Z)', content, re.DOTALL)
            if match:
                clean_text = match.group(1).strip()
            else:
                print(f"⚠️  Geen clean_text: {file_path.name}")
                continue

            fuzzy_hash = hashlib.sha256(clean_text.encode('utf-8')).hexdigest()
            web_path = str(file_path).replace('\\', '/')

            fuzzy_hashes[fuzzy_hash] = web_path
            clean_texts[web_path] = clean_text

    # Bouw JS bestand
    js_content = """// ==================== OFFICIAL FUZZY HASHES + CLEAN TEXTS ====================
// Auto-generated by update-clean-texts.py - DO NOT EDIT MANUALLY

window.officialFuzzyHashes = {
"""

    for h, p in sorted(fuzzy_hashes.items()):
        js_content += f'  "{h}": "{p}",\n'

    js_content = js_content.rstrip(',\n') + "\n};\n\nwindow.officialCleanTexts = {\n"

    for p, t in sorted(clean_texts.items()):
        js_content += f'  "{p}": "{escape_for_js(t)}",\n'

    js_content = js_content.rstrip(',\n') + "\n};\n"

    js_file.write_text(js_content, encoding='utf-8')
    print(f"🎉 Rebuild completed with {len(fuzzy_hashes)} entries!")
    print(f"   → {js_file}")

if __name__ == "__main__":
    rebuild_clean_texts()